# Generated by Django 4.1.3 on 2024-10-14 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_variant_product_product_variants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variants',
            field=models.ManyToManyField(to='home.variant'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='hashtags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='music',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.music'),
        ),
    ]
